name: project3y21
description: Project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # StateManagement
  flutter_bloc:
  tuple:
  freezed_annotation:
  # JsonParser
  json_annotation:
  # Http Client
  dio:
  #Svg Loader
  flutter_svg:
  # Local Persist
  shared_preferences:
  # Simple direct Service Locator
  get_it:
  #auth_nav
  auth_nav:
    git: https://github.com/dangngocduc/auth_nav

  oauth2_dio:
    git: https://github.com/dangngocduc/oauth2_dio
  intl:
  connectivity:
  network_info_plus: 2.1.3
  speech_to_text: 5.5.0
#  alan_voice: ^3.6.0
  avatar_glow: 2.0.2
  socket_io_client: 2.0.0-beta.4-nullsafety.0
  firebase_database: 9.0.15
  flutter_launcher_icons: 0.9.2
  fluttertoast: 8.0.9
  cryptography: ^2.0.5
  cryptography_flutter: ^2.0.2
  dcdg: ^4.0.1
  geolocator: 8.2.1
  flutter_colorpicker: ^1.0.3
  supabase: ^0.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  json_serializable:
  freezed:
  flutter_lints: ^1.0.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo_3y21.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
