name: project3y21
description: Project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # StateManagement
  flutter_bloc:
  tuple:
  freezed_annotation:
  # JsonParser
  json_annotation:
  # Http Client
  dio:
  #Svg Loader
  flutter_svg:
  # Local Persist
  shared_preferences:
  # Simple direct Service Locator
  get_it:
  #auth_nav
  auth_nav:
    git: https://github.com/dangngocduc/auth_nav

  oauth2_dio:
    git: https://github.com/dangngocduc/oauth2_dio
  intl:
  connectivity:
  wifi_info_flutter:
  speech_to_text: 5.4.3
  alan_voice: 3.3.0
  avatar_glow: 2.0.2
  socket_io_client: 1.0.2
  control_pad: ^1.1.1+1
  firebase_database: 9.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  json_serializable:
  freezed:
  flutter_lints: ^1.0.4
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
